apiVersion: v1
kind: Template
labels:
  app: paci
  template: paci-template
metadata:
  name: paci
parameters:
  - description: Git source URI for Jenkins S2I
    name: JENKINS_REPO_URL
    value: https://github.com/jlebon/paci
  - description: Git branch/tag reference for Jenkins S2I
    name: JENKINS_REPO_REF
    value: master

objects:

  ### JENKINS MASTER ###

  # use our own "gated" imagestream for the Jenkins master so we can test new
  # images before upgrading
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-s2i
    spec:
      tags:
        - name: stable
          from:
            kind: DockerImage
            # 2.164.2
            name: docker.io/openshift/jenkins-2-centos7@sha256:19f37019978e9fa37d5571ab39954db5ed9bcb9d0aaedac2ba8cf6d4b4883284
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins
    spec:
      source:
        type: Git
        git:
          uri: ${JENKINS_REPO_URL}
          ref: ${JENKINS_REPO_REF}
        contextDir: jenkins/bc/master
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins-s2i:stable
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: jenkins:2
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

  ### JENKINS SLAVE ###

  # keep a local copy of the Jenkins slave image so we're not constantly pulling
  # it each time from docker.io
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-slave-base-centos7
    spec:
      lookupPolicy:
        # this allows e.g. the pipeline to directly reference the imagestream
        local: true
      tags:
        - name: latest
          from:
            kind: DockerImage
            # target :latest for now
            name: docker.io/openshift/jenkins-slave-base-centos7:latest
          importPolicy:
            scheduled: true
