// XXX: extend openshift/jenkins S2I builder so we can easily bake custom cloud
// configs in config.xml.tpl so we don't need to `podTemplate` each time
podTemplate(label: 'papr-slave', cloud: 'openshift', containers: [
    // XXX: directly using the clusterIP is the only way I could get this to
    // work -- using 'docker-registry.default.svc.cluster.local' fails
    containerTemplate(name: 'jnlp', image: '172.30.1.1:5000/papr/papr-slave',
                      args: '${computer.jnlpmac} ${computer.name}')
    ]) {

    node('papr-slave') {
      checkout scm
      sh "ls -la"
      sh "jenkins-jobs --version"
      sh "env | sort"
    }
}
